---
kind: pipeline
name: linux-pipeline-jdk8
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: mavenjdk8
    pull: always
    image: docker.io/maven:3.8.6-eclipse-temurin-8
    commands:
      - mvn -V clean verify --fail-at-end --batch-mode
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - target/site/jacoco/jacoco.xml