---
kind: pipeline
name: linux-pipeline-jdk11
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: mavenjdk11
    pull: if-not-exists
    image: docker.io/maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - git config --global user.email "noreply@dependency-plugin.invalid"
      - git config --global user.name "dependency-update-maven-plugin"
      - |
        ./mvnw \
          --show-version \
          --errors \
          --fail-at-end \
          --batch-mode \
          --no-transfer-progress \
          verify \
          site site:stage \
          -Pdocs
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - target/site/jacoco/jacoco.xml
