---
kind: pipeline
name: linux-pipeline-jdk8
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: mavenjdk8
    pull: always
    image: docker.io/maven:3.6.3-jdk-8-slim
    commands:
      - apt update
      - apt install git -y
      - mvn -V verify site site:stage --fail-at-end --batch-mode -Pdocs
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - target/site/jacoco/jacoco.xml
