---
kind: pipeline
name: linux-pipeline-jdk8
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: mavenjdk8
    pull: if-not-exists
    image: adoptopenjdk/openjdk8-openj9:ubi
    commands:
      - dnf install --quiet --assumeyes ca-certificates git openssl
      - java -version
      - |
        ./mvnw \
        --show-version \
        --no-transfer-progress \
        --errors \
        --fail-at-end \
        --batch-mode \
        verify site site:stage \
        -Pdocs
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - target/site/jacoco/jacoco.xml
