name: MavenBuild

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  jdk:
    name: "JDK 17 Eclipse Temurin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-jdk-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64            
      - name: 'Build'
        run: |
          git config --global user.email "noreply@dependency-plugin.invalid"
          git config --global user.name "dependency-update-maven-plugin"
          git config --global init.defaultBranch main
          ./mvnw \
          --show-version \
          --fail-at-end \
          --batch-mode \
          --no-transfer-progress \
          clean verify \
          site site:stage \
          -Pdocs
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: false
